blog/urls.py
from django.urls import path
from . import views
from blog import views

# 유저가 업로드한 파일을 보기위한 설정
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("posts/", views.PostList.as_view(), name="postList"),
    path("posts/<int:post_id>/", views.PostDetail.as_view(), name="postDetail"),
    path("posts/add/", views.PostAdd.as_view(), name="post_add"),
]

# 유저가 업로드한 파일을 보기위한 설정
urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT,
)

app_name = "blog"

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog.urls")),
]

app_name = "root"

blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField("포스트 제목", max_length=100)
    content = models.TextField("포스트 내용")
    thumbnail = models.ImageField("이미지", upload_to="post", blank=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField("댓글 내용")

    def __str__(self):
        return f"{self.post.title}의 댓글 (ID : {self.id})"
    

blog/forms.py
from django import forms
from . import models

# 게시물 폼
class AddPostForm(forms.ModelForm):
    class Meta:
        model = models.Post

        fields = ["title", "content", "thumbnail"]

        labels = {
            "title":"제목",
            "content":"내용 ",
            "thumbnail":"썸네일"
        }

# 댓글 폼
class AddCommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment

        fields = ["content"]

        labels = {
            "content":""
        }

blog/views.py
from typing import Any
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView, FormView
from django.urls import reverse_lazy
from . import models
from . import forms

# Create your views here.
class IndexView(TemplateView):
    template_name = "index.html"

class PostList(TemplateView):
    template_name = "post_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        posts = models.Post.objects.all()

        context["posts"] = posts

        return context
    
class PostDetail(FormView):
    template_name = "post_detail.html"

    form_class = forms.AddCommentForm

    # 화면에 표시할 데이터 보내주기
    def get_context_data(self, **kwargs) :
        context = super().get_context_data(**kwargs)

        self.post_id = self.kwargs['post_id']

        post = models.Post.objects.get(id=self.post_id)

        context["post"] = post

        return context
    # 폼이 전달되었을 때 처리
    def form_valid(self, form):
        post_id = self.kwargs["post_id"]

        post = models.Post.objects.get(id=post_id)

        form.instance.post = post
        form.save()

        return super().form_valid(form)
    
    # 성공 후 리다이렉트 url 지정
    def get_success_url(self):

        success_url = reverse_lazy('blog:postDetail', kwargs={"post_id": self.kwargs["post_id"]})

        return success_url
    


class PostAdd(FormView) :
    template_name = "post_add.html"

    form_class = forms.AddPostForm

    posted_id = None

    def form_valid(self, form):

        # 이미지 파일 받기
        thumbnail = form.cleaned_data["thumbnail"]

        form.instance.thumbnail = thumbnail

        form.save()

        self.posted_id = form.instance.id
        
        return super().form_valid(form)
    
    def get_success_url(self):
        # 요청 성공 후 이동할 postID와 페이지 반환

        success_url = reverse_lazy('blog:postDetail', kwargs={"post_id": self.posted_id})
   
        return success_url
    


        

templates/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div id="index">
    <h1><a href="{% url "blog:postList" %}">Pylog</a></h1>
    <small>Lift is short, You need Python</small>
    </div>
</body>
</html>

templates/post_add.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <div id="navbar">
        <h1>Post Add</h1>
    </div>

    <div id="post-add">
        <form method="POST" enctype="multipart/form-data"> 
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit" class="btn btn-primary">작성</button> 
        </form>
    </div>
    
</body>
</html>

templates/post_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="kr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div id="navbar"> 
        {% if post.thumbnail %}
        <img src="{{ post.thumbnail.url }}">
        {% endif %}
        <span>{{ post.title }}</span>
    </div>

    <div id="post-detail">
        <p>{{ post.content | linebreaksbr }}</p>

        <ul class="comments">
            {% for comment in post.comment_set.all %}
            <li class="comment">{{ comment.content }}</li>
            {% empty %}
            <li class="comment-empty">댓글 없음</li>
            {% endfor %}
        </ul>

        <form method="POST">

            {% csrf_token %}

            <textarea name="content"></textarea>
            <button class="btn btn-primary" type="submit">댓글 작성</button>

        </form>

    </div>
</body>
</html>

templates/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div id="navbar">
        <h1>pylog</h1>
        <a href="{% url "blog:post_add" %}" class="btn btn-primary">글 작성</a>
    </div>


    <div id="post-list">

    <ul class="posts">
        {% for post in posts %}

            <li class="post">
                <div>
                    <a href={% url "blog:postDetail" post_id=post.id %}><h2>{{ post.title }}</h2></a>
                </div>

                <p>{{ post.content }}</p>
                <ul class="comments">
                    {% for comment in  post.comment_set.all %}
                    <li class="comment">{{ comment.content }}</li>
                    {% empty %}
                    <li class="comment-empty">등록된 댓글이 아직 없습니다.</li>
                    {% endfor %}
                </ul>
                {% if post.thumbnail %}
                <img src="{{ post.thumbnail.url }}">
                {% else %}
                <img src="">
                {% endif %}
            </li>

        {% endfor %}
    </ul>

    <div>
    
</body>
</html>